### ISSUE TITLE
.vepgcrop error

### ISSUE THREAD

**Issue by lysoifer** [ilyamaclean/microclimf#6]
I am using runmicro_biga, and it errors with `'unable to find an inherited method for function 'ext' for signature 'array'`. This appears to be coming from .vegpcrop because clump is cropped twice, the second time as a raster, though it is an array. I think removing the line `clump<-.cropraster(vegp$clump,rw,cl)` should solve the issue.

Thanks,
Lydia

**Comment by ilyamaclean** [comment]
Hi Lydia,

I did a major update to the package and didn't quite finish following this through for all the functions. It is on my list of things to do

I

From: Lydia Soifer ***@***.***>
Sent: 08 September 2022 12:59
To: ilyamaclean/microclimf ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ilyamaclean/microclimf] .vepgcrop error (Issue #6)

CAUTION: This email originated from outside of the organisation. Do not click links or open attachments unless you recognise the sender and know the content is safe.


I am using runmicro_biga, and it errors with 'unable to find an inherited method for function 'ext' for signature 'array'. This appears to be coming from .vegpcrop because clump is cropped twice, the second time as a raster, though it is an array. I think removing the line clump<-.cropraster(vegp$clump,rw,cl) should solve the issue.

Thanks,
Lydia

-

**Comment by ilyamaclean** [comment]
This should now be resolved, but let me know if there is still issues

**Comment by lysoifer** [comment]
Thank you. I have found an error in expandtonc(). When running, runmicro_dy with expand=F, mout_mn$trdf=NULL and mout_mx$trdf=NULL. When running expandtonc() with reqhgt>0, .expandclim2 errors because mout$trdf is NULL. I can work around this by running .expandclim(), but am not sure if this is okay or if .expandclim2 is necessary to produce accurate models above the ground.

Thanks,
Lydia

**Comment by ilyamaclean** [comment]
Sorry - handed updated the expandtonc function fully following the package overhaul. Should be fixed now
